apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed-deployment
spec:
  replicas: 1

  selector:
    matchLabels:
      pod: api-feed

  template:
    metadata:
      labels:
        pod: api-feed
    spec:
      containers:
        # containers to run in the Pods
        - name: api-feed
          image: hungapp/udagram-api-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 #informational
      restartPolicy: Always
