apiVersion: v1
kind: Service
metadata:
  name: api-feed-svc
spec:
  selector:
    pod: api-feed
  ports:
    - port: 8080 # targets TCP port 8080 on any Pod with the app: api-feed label; targetPort is the port the container accepts traffic on; port is the abstracted Service port
      protocol: TCP
