apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user-deployment
spec:
  replicas: 1

  selector:
    matchLabels:
      pod: api-user

  template:
    metadata:
      labels:
        pod: api-user
    spec:
      containers:
        # containers to run in the Pods
        - name: api-user
          image: hungapp/udagram-api-user
          imagePullPolicy: Always
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '1024Mi'
              cpu: '500m'
          env:
            - name: AWS_MEDIA_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_MEDIA_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: AWS_REGION
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_HOST
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: POSTGRES_DATABASE

            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: env-secret
                  key: JWT_SECRET
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: env-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: env-secret
                  key: POSTGRES_PASSWORD

      restartPolicy: Always
