apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: hungapp/udagram-frontend
          name: frontend
          imagePullPolicy: Always
          resources:
            requests:
              memory: '1024Mi'
              cpu: '300m'
            limits:
              memory: '1536Mi'
              cpu: '500m'
          ports:
            - containerPort: 80
      restartPolicy: Always
