apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - port: 8100 # targets TCP port on any Pod with the app: frontend label; targetPort is the port the container accepts traffic on; port is the abstracted Service port
      protocol: TCP
