apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy-deployment
  labels:
    service: reverse-proxy
spec:
  replicas: 2

  selector:
    matchLabels:
      service: reverse-proxy

  template:
    metadata:
      labels:
        service: reverse-proxy
    spec:
      containers:
        # containers to run in the Pods
        - name: reverse-proxy
          image: hungapp/reverse-proxy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
