apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-svc
spec:
  selector:
    service: reverse-proxy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
