version: '3'
services:
  reverse-proxy:
    build: ../../reverse-proxy
    image: ${DOCKER_USERNAME}/reverse-proxy

  frontend:
    build: ../../udagram-frontend
    image: ${DOCKER_USERNAME}/udagram-frontend

  api-user:
    build: ../../udagram-api-user
    image: ${DOCKER_USERNAME}/udagram-api-user

  api-feed:
    build: ../../udagram-api-feed
    image: ${DOCKER_USERNAME}/udagram-api-feed
