apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy-deployment
  labels:
    service: reverseproxy

spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: hungapp/reverse-proxy
          imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: '64Mi'
          #     cpu: '250m'
          #   limits:
          #     memory: '1024Mi'
          #     cpu: '500m'
          ports:
            - containerPort: 8080
      restartPolicy: Always
