apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user-deployment
spec:
  replicas: 1

  selector:
    matchLabels:
      pod: api-user

  template:
    metadata:
      labels:
        pod: api-user
    spec:
      containers:
        # containers to run in the Pods
        - name: api-user
          image: hungapp/udagram-api-user
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 #informational
      restartPolicy: Always
